export const categories = [
    "Personal",
    "Work",
    "Urgent",
    "Home",
    "Health/Fitness",
    "Finance",
    "Shopping",
    "Learning/Education",
    "Social",
    "Travel",
    "Work Projects",
    "Creativity/Projects",
    "Appointments",
    "Maintenance",
    "Family",
    "Work Admin",
    "Self-Care",
    "Important/High Priority",
    "Miscellaneous",
    "Events",
    "Volunteer",
    "Pet Care",
    "Technology/IT",
    "Milestones/Goals",
    "Ideas/Brainstorming",
    "Admin (Personal)",
    "Subscription Management",
    "Study/Research",
    "Other",
];
  