export const categories = [
    "Personal",
    "Work",
    "Urgent",
    "Home",
    "Health/Fitness",
    "Finance",
    "Shopping",
    "Learning/Education",
    "Social",
    "Travel",
    "Creativity/Projects",
    "Appointments",
    "Maintenance",
    "Family",
    "Important/High Priority",
    "Pet Care",
    "Milestones/Goals",
    "Ideas/Brainstorming",
    "Study/Research",
    "Other",
];
  
export const categoryColors = {
    "Personal": "#4A90E2", 
    "Work": "#50E3C2", 
    "Urgent": "#FF0000", 
    "Home": "#F39C12", 
    "Health/Fitness": "#27AE60", 
    "Finance": "#F1C40F", 
    "Shopping": "#1ABC9C", 
    "Learning/Education": "#9B59B6", 
    "Social": "#FF4081", 
    "Travel": "#00B5E2", 
    "Creativity/Projects": "#b3f542",
    "Appointments": "#BDC3C7", 
    "Maintenance": "#73736e", 
    "Family": "#FF7F50", 
    "Important/High Priority": "#D35400", 
    "Pet Care": "#c491c0", 
    "Milestones/Goals": "#bc42f5", 
    "Ideas/Brainstorming": "#f5b642", 
    "Study/Research": "#48668a",
    "Other": "#080807", 
};